version: '3'
services:
  alc-api:
    image: user-manager
    build: ./
    command: npm start
    restart: always
    ports:
      - "1337:1337"
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db